
let movies = [
    {
      id: '0',
      name: "Miss Bala",
      rating: "6.5",
      description : "Young Gloria seeks help from the police when cartel hit men kidnap her friend from a nightclub in Mexico. She soon finds herself in big trouble when a corrupt cop hands her over to the same goons who shot up the place.",
      year : "2019",
      thumnail : 'https://m.media-amazon.com/images/M/MV5BMTcxNzY3Mzk5OF5BMl5BanBnXkFtZTgwNjQwODU1NjM@._V1_UX182_CR0,0,182,268_AL_.jpg',
      poster : 'https://www.sonypictures.com/sites/default/files/styles/max_1300x1300/public/banner-images/2019-03/missbala_herobanner_2572x1100_copyright_0.jpg?itok=qw1YRDH5',
      genres : ['Action', 'Thriller' ],
      trailer : "",
      runtime : '1hr 47min',
      type : 'movies'
    },
    {
      id:'1',
      name: "Ramepage",
      rating: "6.1",
      description : "Primatologist Davis Okoye teams up with a geneticist, Dr. Kate Caldwell, and an albino gorilla, George, to prevent three giant mutated animals from wreaking havoc in Chicago.",
      year : "2018",
      thumnail : 'https://m.media-amazon.com/images/M/MV5BNDA1NjA3ODU3OV5BMl5BanBnXkFtZTgwOTg3MTIwNTM@._V1_UX182_CR0,0,182,268_AL_.jpg',
      poster : 'https://images8.alphacoders.com/913/thumb-1920-913599.jpg',
      genres : ['Action', 'Adventure' ],
      trailer : "",
      runtime : '1hr 42min',
      type : 'movies'
    },
    {
      id: '2',
      name: "Notting Hill",
      rating: "7.1",
      description : "William, a British bookseller, meets and falls in love with Anna, a high-profile American actress. However, their relationship goes through many problems due to their different social statuses.",
      year : "1999",
      thumnail : "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT_7PO2_rEPDxEuvn6wABnIPdVieLWPkxXFVrU2B2wqpXEzJWoP",
      poster : 'https://lh4.googleusercontent.com/proxy/saVIzvtKIWGOLJvhmQhPmFpIKKqcTqy5EZzhX4DqjAL2dxoklOzegNxHdFjuirp3T0aPGvjkAgbt6MJMoZ_mCBYZgg',
      genres : ['Romance', 'Comedy' ],
      trailer : "",
      runtime : '1hr 47min',
      type : 'movies'
    },
    {
      id:'3',
      name: "Extraction",
      rating: "6.9",
      description : "A black-market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord. But in the murky underworld of weapons dealers and drug traffickers, an already deadly mission approaches the impossible.",
      year : "2020",
      thumnail : "https://upload.wikimedia.org/wikipedia/en/8/89/Extraction_%282020_film%29.png",
      poster : "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTKiHDsbCsa0i7NIazK3rWlZ_ht-46fZxDiXZCa8QhmNCra0zeQ&usqp=CAU",
      genres : ['Action' ],
      trailer : "",
      runtime : '1hr 42min',
      type : 'movies'
    },
    {
      id: '4',
      name: "Avengers: Infinity War",
      rating: "8.5",
      description : "The Avengers must stop Thanos, an intergalactic warlord, from getting his hands on all the infinity stones. However, Thanos is prepared to go to any lengths to carry out his insane plan.",
      year : "2019",
      thumnail : 'https://resizing.flixster.com/IYbHbcL6GSCf5-i4YJSiG_D16ZY=/fit-in/200x296.2962962962963/v1.bTsxMjcwMDQ5MztqOzE4NDE2OzEyMDA7MTY4ODsyNTAw',
      poster : "https://www.herocollector.com/Content/ArticleImages/03264ab4-6f4c-45cd-b7cd-278590517bf6.jpg",
      genres : ['Action', 'Sci fi' ],
      trailer : "",
      runtime : '2hr 40min',
      type : 'movies'
    },
    {
      id:'5',
      name: "Trolls World Tour ",
      rating: "6.1",
      description : "Poppy and Branch discover that there are six different troll tribes scattered over six different lands. Each tribe is also devoted to six different kinds of music -- funk, country, techno, classical, pop and rock. ",
      year : "2020",
      thumnail : "https://wallpapercave.com/wp/wp5806886.jpg",
      poster : "https://wallpapercave.com/wp/wp5806873.jpg",
      genres : ['Musical', 'animation' ],
      trailer : "",
      runtime : '1hr 34min',
      type : 'movies'
    },
    {
      id: '6',
      name: "Avengers: Endgame",
      rating: "8.4",
      description : "After Thanos, an intergalactic warlord, disintegrates half of the universe, the Avengers must reunite and assemble again to reinvigorate their trounced allies and restore balance.",
      year : "2019",
      thumnail : "https://picfiles.alphacoders.com/242/thumb-242157.jpg",
      poster : "https://wallpapercave.com/wp/wp4310765.png",
      genres : ['Action', 'Sci Fi' ],
      trailer : "",
      runtime : '3hr 02min',
      type : 'movies'
    },
    {
      id:'7',
      name: "Marriage Story",
      rating: "8.1",
      description : "A stage director and his actor wife struggle through a gruelling, coast-to-coast divorce that pushes them to their personal and creative extremes.",
      year : "2019",
      thumnail : "http://www.impawards.com/2019/posters/marriage_story.jpg",
      poster : "https://i0.wp.com/fangirlish.com/wp-content/uploads/2019/10/MarriageStory.jpg?zoom=2&resize=920%2C425&ssl=1",
      genres : ['Drama', 'Comedy-Drama' ],
      trailer : "",
      runtime : '2hr 17min',
      type : 'movies'
    },
    {
      id: '8',
      name: "MIB International",
      rating: "5.7",
      description : "When aliens that have the ability to shape-shift into humans arrive on Earth, Agent H joins forces with Agent M, a new recruit, to save the planet.",
      year : "2019",
      thumnail : "https://picfiles.alphacoders.com/249/thumb-249634.jpg",
      poster : "https://images6.alphacoders.com/102/thumb-350-1020157.jpg",
      genres : ['Action', 'Sci Fi' ],
      trailer : "",
      runtime : '1hr 47min',
      type : 'movies'
    },
    {
      id:'9',
      name: "6 Underground",
      rating: "6.1",
      description : "Six individuals from all around the globe, each the very best at what they do, have been chosen not only for their skill, but for a unique desire to delete their pasts to change the future.",
      year : "2019",
      thumnail : "https://www.joblo.com/assets/images/joblo/posters/2019/12/6-underground-poster1.jpg",
      poster : 'https://wallpapercave.com/wp/wp5099327.png',
      genres : ['Action', 'Thriller' ],
      trailer : "",
      runtime : '1hr 42min',
      type : 'movies'
    },
    {
      id:'10',
      name: "Bloodshot",
      rating: "5.7",
      description : "Based on the Valiant Comics character of the same name; Bloodshot stars Vin Diesel as Marine Ray Garrison. When he and his wife are murdered, Ray is resurrected by a secret team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine.",
      year : "2019",
      thumnail : "https://static.akacdn.ru/files/images/2020/03/b74cc39b8f9d29e31f5ffe3bd8c547bd.jpg",
      poster : 'https://wallpapercave.com/wp/wp5099327.png',
      genres : ['Action', 'Thriller' ],
      trailer : "",
      runtime : '1hr 42min',
      type : 'movies'
    },
    {
      id:'11',
      name: "The 100",
      rating: "7.7",
      description : "A nuclear conflict has decimated civilisation. Ninety-seven years later, a spaceship accommodating humanity's lone survivors despatches 100 juvenile delinquents back to the Earth.",
      year : "2014-2020",
      thumnail : "https://i.pinimg.com/236x/a3/60/72/a360728a71d61a54d2ed6ab7570f113e.jpg",
      poster : 'https://cdn.hipwallpaper.com/m/13/70/lKuc5j.jpg',
      genres : ['Drama', 'Thriller' ],
      trailer : "",
      season : 7,
      type : 'series'
    },
    {
      id:'12',
      name: "F.R.I.E.N.D.S",
      rating: "8.9",
      description : "Follow the lives of six reckless adults living in Manhattan, as they indulge in adventures which make their lives both troublesome and happening.",
      year : "1994-2004",
      thumnail : "https://i.pinimg.com/564x/7f/e9/06/7fe90609ac8ecde2eea7b9763dfcbaaa.jpg",
      poster : 'https://wallpapercave.com/wp/75KenAW.jpg',
      genres : ['Comedy', 'Romance' ],
      trailer : "",
      season : 10,
      type : 'series'
    },
    {
      id:'13',
      name: "Prision Break",
      rating: "8.3",
      description : "An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.",
      year : "2005",
      thumnail : "https://i.pinimg.com/236x/03/37/ac/0337acb9870c79a9ddf8f30531c2cd9a.jpg",
      poster : 'https://wallpapercave.com/wp/wp2879190.jpg',
      genres : ['Crime', 'Action' ],
      trailer : "",
      season : 5,
      type : 'series'
    },

  ];

  export default movies
